### ISSUE TITLE
app crashes when trying to save

### ISSUE THREAD

**Issue by muelli** [flathub/com.github.taiko2k.avvie#3]
This is probably not flatpak specific, but let me file it here, as I am experiencing it with the flatpaked version.

```
Traceback (most recent call last):
  File "/app/lib/python3.7/site-packages/piexif/_dump.py", line 272, in _value_to_bytes
    value_str = raw_value + b"\x00" * (4 - length)
TypeError: can only concatenate tuple (not "bytes") to tuple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/lib/python3.7/site-packages/piexif/_dump.py", line 337, in _dict_to_bytes
    offset)
  File "/app/lib/python3.7/site-packages/piexif/_dump.py", line 274, in _value_to_bytes
    raise ValueError("Got invalid type to convert.")
ValueError: Got invalid type to convert.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/bin/main.py", line 1137, in save
    picture.export()
  File "/app/bin/main.py", line 481, in export
    exif_bytes = piexif.dump(self.exif)
  File "/app/lib/python3.7/site-packages/piexif/_dump.py", line 68, in dump
    exif_set = _dict_to_bytes(exif_ifd, "Exif", zeroth_length)
  File "/app/lib/python3.7/site-packages/piexif/_dump.py", line 341, in _dict_to_bytes
    '{} in {} IFD. Got as {}.'.format(key, ifd, type(ifd_dict[key]))
ValueError: "dump" got wrong type of exif value.
41729 in Exif IFD. Got as <class 'int'>.
```

**Comment by Taiko2k** [comment]
Seems to be hitting this issue here https://github.com/hMatoba/Piexif/issues/95. Will have to wait for that issue to be resolved, or I could just implement the workaround mentioned there.

In the mean time you might be able to avoid this crash in Avvie by choosing not to keep the exif data.
